package main

func init() {
	for k, v := range logStringsZH() {
		uiBundles["zh"][k] = v
	}
	for k, v := range logStringsEN() {
		uiBundles["en"][k] = v
	}
	for k, v := range logStringsPT() {
		uiBundles["pt"][k] = v
	}
}

func logStringsZH() map[string]string {
	return map[string]string{
		"log_agent_start":           "打印服务启动，版本 %s",
		"log_agent_startup":         "已连接：%s | 已映射档口：%d",
		"log_schedule_line":         "  营业时间 %s",
		"log_schedule_tz":           "  时区：%s",
		"log_schedule_disabled":     "  营业时间：未启用（代理运行期间持续轮询）",
		"log_poll_intervals":        "  轮询间隔（秒）：打印后=%d，活跃=%d，活跃窗口=%d，空闲=%d，繁忙=%d，歇业检查=%d",
		"log_runtime_config_fail":   "无法拉取云端营业时间/轮询设置，使用本机配置",
		"log_schedule_error":        "营业时间判断异常",
		"log_outside_schedule_sleep": "非营业时间，暂停拉单约 %s",
		"log_outside_schedule":      "非营业时间，暂停拉单",
		"log_schedule_resume":       "进入营业时间，恢复拉单",
		"log_heartbeat_error":       "心跳上报失败",
		"log_pending_jobs_error":    "无法连接 Mesa 拉取打印任务",
		"log_fetched_pending":       "拉取到 %d 条待打印任务",
		"log_skipped_expired":       "已跳过超过 10 分钟的旧任务（单号 %s）",
		"log_printer_not_ready":     "打印机不可达 [%s] 档口 %s：%s",
		"log_job_held_pending":        "任务保持待处理（非失败）：单号 %s，打印机 %s — 稍后重试",
		"log_prepare_print_error":   "打印前检查失败（单号 %s）：%s",
		"log_job_still_pending":     "任务仍为 pending（单号 %s，步骤 %s），请查 Mesa 连接",
		"log_printing_job":          "开始打印：单号 %s，档口 %s，打印机 %s（%s）",
		"log_queue_reorder_printer": "打印机 [%s] 不可达，先处理其他打印机任务（触发档口 %s）",
		"log_receipt_deferred":      "结账小票等待打印机映射（最多约 10 分钟）",
		"log_queue_try_other":       "当前任务暂不可打印（单号 %s），先处理队列中其他任务",
		"log_queue_all_blocked":     "本批任务均暂不可打印，稍后重试",
		"log_route_error":           "任务路由失败（单号 %s，档口 %s）：%s",
		"log_patch_job_failed":      "更新任务状态失败 %s（单号 %s）",
		"log_patch_job_retry_ok":    "重试更新任务状态成功 %s（单号 %s）",
		"log_patch_job_retry_failed": "重试更新任务状态仍失败 %s（单号 %s）",
		"log_print_failed":          "打印失败（单号 %s，档口 %s，%s）：%s",
		"log_print_failed_stuck":    "打印失败且未能标为 failed（单号 %s，%s），可能卡在 processing",
		"log_print_ok_patch_stuck":  "已出纸但未能标为 done（单号 %s，%s），请在后台核对",
		"log_printed_ok":            "已打印：%s → %s（单号 %s）",
		"log_pairing_required":      "需要配对：请在浏览器中完成配对向导（托盘图标应可见）",
		"log_setup_wizard":          "未配置打印机，正在打开映射向导",
		"log_no_station_mapping":    "尚未映射出品档口，请在「打印机设置」中配置",
		"log_saved_config":          "配置已保存：%s",
		"log_wizard_open":           "请在浏览器中打开：%s",
		"log_routing_sync_fail":     "档口映射同步到 Mesa 失败",
		"log_routing_sync_http":     "档口映射同步失败（HTTP %d）",
		"log_routing_sync_ok":       "档口映射已同步到 Mesa（%d 个）",
		"log_station_maps_saved":    "已保存 %d 个档口打印机映射",
		"log_test_print_station":    "试打：档口 %s",
		"log_pair_ok":               "配对成功",
		"log_browser_open_fail":     "无法自动打开浏览器",
		"log_tray_ui_locale":        "界面语言已设为：%s",
	}
}

func logStringsEN() map[string]string {
	return map[string]string{
		"log_agent_start":           "Print service started, version %s",
		"log_agent_startup":         "Connected: %s | mapped stations: %d",
		"log_schedule_line":         "  Hours %s",
		"log_schedule_tz":           "  Timezone: %s",
		"log_schedule_disabled":     "  Schedule: off (polling 24/7 while running)",
		"log_poll_intervals":        "  Poll intervals (sec): after_print=%d warm=%d warm_window=%d idle=%d busy=%d closed_check=%d",
		"log_runtime_config_fail":   "Could not fetch cloud schedule/poll; using local settings",
		"log_schedule_error":        "Schedule check error",
		"log_outside_schedule_sleep": "Outside business hours, pausing ~%s",
		"log_outside_schedule":      "Outside business hours, not polling",
		"log_schedule_resume":       "Business hours started, resuming polls",
		"log_heartbeat_error":       "Heartbeat upload failed",
		"log_pending_jobs_error":    "Cannot reach Mesa to fetch print jobs",
		"log_fetched_pending":       "Fetched %d pending print job(s)",
		"log_skipped_expired":       "Skipped job older than 10 minutes (id %s)",
		"log_printer_not_ready":     "Printer not reachable [%s] station %s: %s",
		"log_job_held_pending":        "Job held pending (not failed): id %s, printer %s — will retry",
		"log_prepare_print_error":   "Pre-print check failed (id %s): %s",
		"log_job_still_pending":     "Job still pending (id %s, step %s); check Mesa connectivity",
		"log_printing_job":          "Printing: id %s, station %s, printer %s (%s)",
		"log_queue_reorder_printer": "Printer [%s] unreachable; processing other printers first (station %s)",
		"log_receipt_deferred":      "Receipt waiting for printer mapping (up to ~10 min)",
		"log_queue_try_other":       "Deferring blocked job (id %s), trying others in queue",
		"log_queue_all_blocked":     "All jobs in batch blocked; will retry shortly",
		"log_route_error":           "Job routing failed (id %s, station %s): %s",
		"log_patch_job_failed":      "Could not update job status %s (id %s)",
		"log_patch_job_retry_ok":    "Retry update job status OK %s (id %s)",
		"log_patch_job_retry_failed": "Retry update job status failed %s (id %s)",
		"log_print_failed":          "Print failed (id %s, station %s, %s): %s",
		"log_print_failed_stuck":    "Print failed and could not mark failed (id %s, %s); may be stuck processing",
		"log_print_ok_patch_stuck":  "Paper sent but could not mark done (id %s, %s); check dashboard",
		"log_printed_ok":            "Printed: %s → %s (id %s)",
		"log_pairing_required":      "Pairing required — complete the browser wizard",
		"log_setup_wizard":          "No printer mapped — opening setup wizard",
		"log_no_station_mapping":    "No station printers mapped — open Printer settings",
		"log_saved_config":          "Config saved: %s",
		"log_wizard_open":           "Open in browser: %s",
		"log_routing_sync_fail":     "Failed to sync station mapping to Mesa",
		"log_routing_sync_http":     "Station mapping sync failed (HTTP %d)",
		"log_routing_sync_ok":       "Station mapping synced to Mesa (%d)",
		"log_station_maps_saved":    "Saved %d station printer mapping(s)",
		"log_test_print_station":    "Test print: station %s",
		"log_pair_ok":               "Pairing saved",
		"log_browser_open_fail":     "Could not open browser automatically",
		"log_tray_ui_locale":        "Interface language set to: %s",
	}
}

func logStringsPT() map[string]string {
	return map[string]string{
		"log_agent_start":           "Serviço de impressão iniciado, versão %s",
		"log_agent_startup":         "Ligado: %s | estações mapeadas: %d",
		"log_schedule_line":         "  Horário %s",
		"log_schedule_tz":           "  Fuso: %s",
		"log_schedule_disabled":     "  Horário: desativado (consulta 24/7 enquanto corre)",
		"log_poll_intervals":        "  Intervalos (s): após_impressão=%d ativo=%d janela=%d inativo=%d ocupado=%d fechado=%d",
		"log_runtime_config_fail":   "Não foi possível obter horário/poll da nuvem; usa definições locais",
		"log_schedule_error":        "Erro ao verificar horário",
		"log_outside_schedule_sleep": "Fora do horário, pausa ~%s",
		"log_outside_schedule":      "Fora do horário, sem consultas",
		"log_schedule_resume":       "Horário de funcionamento — a retomar consultas",
		"log_heartbeat_error":       "Falha ao enviar heartbeat",
		"log_pending_jobs_error":    "Sem ligação ao Mesa para obter trabalhos",
		"log_fetched_pending":       "Obtidos %d trabalhos pendentes",
		"log_skipped_expired":       "Ignorado trabalho com mais de 10 min (id %s)",
		"log_printer_not_ready":     "Impressora inacessível [%s] estação %s: %s",
		"log_job_held_pending":        "Trabalho em espera (não falhou): id %s, %s — nova tentativa em breve",
		"log_prepare_print_error":   "Falha na verificação pré-impressão (id %s): %s",
		"log_job_still_pending":     "Trabalho ainda pending (id %s, passo %s); verifique ligação ao Mesa",
		"log_printing_job":          "A imprimir: id %s, estação %s, impressora %s (%s)",
		"log_queue_reorder_printer": "Impressora [%s] inacessível; outras impressoras primeiro (estação %s)",
		"log_receipt_deferred":      "Conta à espera de impressora mapeada (até ~10 min)",
		"log_queue_try_other":       "Tarefa bloqueada (id %s); a tentar outras na fila",
		"log_queue_all_blocked":     "Todos os trabalhos do lote bloqueados; nova tentativa em breve",
		"log_route_error":           "Falha de encaminhamento (id %s, estação %s): %s",
		"log_patch_job_failed":      "Falha ao atualizar estado %s (id %s)",
		"log_patch_job_retry_ok":    "Repetição atualizar estado OK %s (id %s)",
		"log_patch_job_retry_failed": "Repetição atualizar estado falhou %s (id %s)",
		"log_print_failed":          "Falha de impressão (id %s, estação %s, %s): %s",
		"log_print_failed_stuck":    "Falha de impressão sem marcar failed (id %s, %s)",
		"log_print_ok_patch_stuck":  "Impresso mas não marcou done (id %s, %s)",
		"log_printed_ok":            "Impresso: %s → %s (id %s)",
		"log_pairing_required":      "Emparelhamento necessário — conclua no browser",
		"log_setup_wizard":          "Sem impressora — a abrir assistente",
		"log_no_station_mapping":    "Sem estações mapeadas — abra Definições de impressora",
		"log_saved_config":          "Configuração guardada: %s",
		"log_wizard_open":           "Abra no browser: %s",
		"log_routing_sync_fail":     "Falha ao sincronizar mapeamento com Mesa",
		"log_routing_sync_http":     "Sincronização falhou (HTTP %d)",
		"log_routing_sync_ok":       "Mapeamento sincronizado (%d)",
		"log_station_maps_saved":    "Guardadas %d estações",
		"log_test_print_station":    "Teste: estação %s",
		"log_pair_ok":               "Emparelhamento guardado",
		"log_browser_open_fail":     "Não foi possível abrir o browser",
		"log_tray_ui_locale":        "Idioma da interface: %s",
	}
}
