import type { UILanguage } from '@/lib/i18n';
import { KITCHEN_ITEM_STATUS_LABEL } from '@/lib/kitchen-progress-display';

/** Kitchen-screen UI copy (zh/en primary; others fall back to en). */
export const KITCHEN_SCREEN_TEXT: Record<
  UILanguage,
  {
    screensTitle: string;
    screensEmpty: string;
    screensEmptyHint: string;
    openScreen: string;
    backToScreens: string;
    viewByTable: string;
    viewByDish: string;
    prep: string;
    prepBusy: string;
    print: string;
    printBusy: string;
    maximize: string;
    restore: string;
    selectLines: string;
    selectPrintLines: string;
    selectAll: string;
    deselectAll: string;
    noLines: string;
    statusPending: string;
    statusCooking: string;
    statusReady: string;
    statusDone: string;
    /** By-dish L1: workbench portion total for this dish. */
    portionBadge: string;
    /** By-dish L1: distinct table count (never line/qty count). */
    tablesCountBadge: string;
    tablesLabel: string;
    waitMinutes: string;
    expandGroup: string;
    collapseGroup: string;
    readyRailShow: string;
    readyRailHide: string;
    readyRailEmpty: string;
    prepSuccess: string;
    prepFailed: string;
    printSuccess: string;
    printFailed: string;
    conflict: string;
    readyAfterMinutesLabel: string;
    readyAfterMinutesHint: string;
    readyAfterMinutesUnit: string;
    readyAfterMinutesSave: string;
    readyAfterMinutesSaved: string;
    readyAfterMinutesSaveFail: string;
  }
> = {
  zh: {
    screensTitle: '后厨大屏',
    screensEmpty: '暂无大屏',
    screensEmptyHint: '请店主在设置中配置后厨大屏与档口。',
    openScreen: '打开',
    backToScreens: '返回大屏列表',
    viewByTable: '按桌',
    viewByDish: '按菜',
    prep: '备餐',
    prepBusy: '备餐中…',
    print: '打印',
    printBusy: '打印中…',
    maximize: '最大化',
    restore: '复原',
    selectLines: '勾选后点击备餐',
    selectPrintLines: '勾选后点击打印',
    selectAll: '全选',
    deselectAll: '取消全选',
    noLines: '暂无待备餐菜品',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.zh.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.zh.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.zh.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.zh.done,
    portionBadge: '共 {n} 份',
    tablesCountBadge: '共 {n} 桌',
    tablesLabel: '桌：{tables}',
    waitMinutes: '等 {n} 分',
    expandGroup: '展开',
    collapseGroup: '收起',
    readyRailShow: '已备餐/已出餐 · {n}',
    readyRailHide: '收起',
    readyRailEmpty: '暂无已备餐或已出餐',
    prepSuccess: '已备餐',
    prepFailed: '备餐失败，请重试',
    printSuccess: '已打印',
    printFailed: '打印失败，请重试',
    conflict: '数据已更新，请重试',
    readyAfterMinutesLabel: '已备餐 → 已出餐等待时间',
    readyAfterMinutesHint: '到期后下方栏显示「已出餐」，全店统一。',
    readyAfterMinutesUnit: '分钟',
    readyAfterMinutesSave: '保存',
    readyAfterMinutesSaved: '已保存',
    readyAfterMinutesSaveFail: '保存失败，请重试',
  },
  en: {
    screensTitle: 'Kitchen screens',
    screensEmpty: 'No screens configured',
    screensEmptyHint: 'Ask the owner to configure kitchen screens and stations in settings.',
    openScreen: 'Open',
    backToScreens: 'Back to screens',
    viewByTable: 'By table',
    viewByDish: 'By dish',
    prep: 'Prep',
    prepBusy: 'Prepping…',
    print: 'Print',
    printBusy: 'Printing…',
    maximize: 'Maximize',
    restore: 'Restore',
    selectLines: 'Select lines, then prep',
    selectPrintLines: 'Select lines, then print',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    noLines: 'No dishes waiting',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.en.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.en.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.en.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.en.done,
    portionBadge: '{n} pcs',
    tablesCountBadge: '{n} tables',
    tablesLabel: 'Tables: {tables}',
    waitMinutes: '{n}m wait',
    expandGroup: 'Expand',
    collapseGroup: 'Collapse',
    readyRailShow: 'Prepped / ready · {n}',
    readyRailHide: 'Hide',
    readyRailEmpty: 'No prepped or ready dishes',
    prepSuccess: 'Prepped',
    prepFailed: 'Prep failed — try again',
    printSuccess: 'Printed',
    printFailed: 'Print failed — try again',
    conflict: 'Board updated — please retry',
    readyAfterMinutesLabel: 'Prepped → ready wait',
    readyAfterMinutesHint: 'After this time, rows show Ready for the whole store.',
    readyAfterMinutesUnit: 'min',
    readyAfterMinutesSave: 'Save',
    readyAfterMinutesSaved: 'Saved',
    readyAfterMinutesSaveFail: 'Save failed — try again',
  },
  pt: {
    screensTitle: 'Ecras de cozinha',
    screensEmpty: 'Sem ecras configurados',
    screensEmptyHint: 'Peca ao dono para configurar ecras e estacoes nas definicoes.',
    openScreen: 'Abrir',
    backToScreens: 'Voltar aos ecras',
    viewByTable: 'Por mesa',
    viewByDish: 'Por prato',
    prep: 'Preparar',
    prepBusy: 'A preparar…',
    print: 'Imprimir',
    printBusy: 'A imprimir…',
    maximize: 'Maximizar',
    restore: 'Restaurar',
    selectLines: 'Selecione e prepare',
    selectPrintLines: 'Selecione e imprima',
    selectAll: 'Selecionar tudo',
    deselectAll: 'Desmarcar',
    noLines: 'Sem pratos a preparar',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.pt.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.pt.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.pt.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.pt.done,
    portionBadge: '{n} un.',
    tablesCountBadge: '{n} mesas',
    tablesLabel: 'Mesas: {tables}',
    waitMinutes: '{n} min',
    expandGroup: 'Expandir',
    collapseGroup: 'Recolher',
    readyRailShow: 'Preparado / pronto · {n}',
    readyRailHide: 'Ocultar',
    readyRailEmpty: 'Sem pratos preparados ou prontos',
    prepSuccess: 'Preparado',
    prepFailed: 'Falha ao preparar',
    printSuccess: 'Impresso',
    printFailed: 'Falha ao imprimir',
    conflict: 'Quadro atualizado — tente de novo',
    readyAfterMinutesLabel: 'Preparado → pronto (espera)',
    readyAfterMinutesHint: 'Apos este tempo, linhas mostram Pronto em toda a loja.',
    readyAfterMinutesUnit: 'min',
    readyAfterMinutesSave: 'Guardar',
    readyAfterMinutesSaved: 'Guardado',
    readyAfterMinutesSaveFail: 'Falha ao guardar',
  },
  es: {
    screensTitle: 'Pantallas de cocina',
    screensEmpty: 'Sin pantallas',
    screensEmptyHint: 'Pida al dueno configurar pantallas y estaciones.',
    openScreen: 'Abrir',
    backToScreens: 'Volver',
    viewByTable: 'Por mesa',
    viewByDish: 'Por plato',
    prep: 'Preparar',
    prepBusy: 'Preparando…',
    print: 'Imprimir',
    printBusy: 'Imprimiendo…',
    maximize: 'Maximizar',
    restore: 'Restaurar',
    selectLines: 'Seleccione y prepare',
    selectPrintLines: 'Seleccione e imprima',
    selectAll: 'Seleccionar todo',
    deselectAll: 'Deseleccionar',
    noLines: 'Sin platos pendientes',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.es.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.es.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.es.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.es.done,
    portionBadge: '{n} uds',
    tablesCountBadge: '{n} mesas',
    tablesLabel: 'Mesas: {tables}',
    waitMinutes: '{n} min',
    expandGroup: 'Expandir',
    collapseGroup: 'Cerrar',
    readyRailShow: 'Preparado / listo · {n}',
    readyRailHide: 'Ocultar',
    readyRailEmpty: 'Sin platos preparados o listos',
    prepSuccess: 'Preparado',
    prepFailed: 'Error al preparar',
    printSuccess: 'Impreso',
    printFailed: 'Error al imprimir',
    conflict: 'Tablero actualizado — reintente',
    readyAfterMinutesLabel: 'Preparado → listo (espera)',
    readyAfterMinutesHint: 'Tras este tiempo, las filas muestran Listo en toda la tienda.',
    readyAfterMinutesUnit: 'min',
    readyAfterMinutesSave: 'Guardar',
    readyAfterMinutesSaved: 'Guardado',
    readyAfterMinutesSaveFail: 'Error al guardar',
  },
  fr: {
    screensTitle: 'Ecrans cuisine',
    screensEmpty: 'Aucun ecran',
    screensEmptyHint: 'Demandez au gerant de configurer les ecrans.',
    openScreen: 'Ouvrir',
    backToScreens: 'Retour',
    viewByTable: 'Par table',
    viewByDish: 'Par plat',
    prep: 'Preparer',
    prepBusy: 'Preparation…',
    print: 'Imprimer',
    printBusy: 'Impression…',
    maximize: 'Agrandir',
    restore: 'Restaurer',
    selectLines: 'Selectionnez puis preparez',
    selectPrintLines: 'Selectionnez puis imprimez',
    selectAll: 'Tout select.',
    deselectAll: 'Tout deselect.',
    noLines: 'Aucun plat en attente',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.fr.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.fr.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.fr.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.fr.done,
    portionBadge: '{n} pcs',
    tablesCountBadge: '{n} tables',
    tablesLabel: 'Tables : {tables}',
    waitMinutes: '{n} min',
    expandGroup: 'Ouvrir',
    collapseGroup: 'Fermer',
    readyRailShow: 'Prepare / pret · {n}',
    readyRailHide: 'Masquer',
    readyRailEmpty: 'Aucun plat prepare ou pret',
    prepSuccess: 'Prepare',
    prepFailed: 'Echec preparation',
    printSuccess: 'Imprime',
    printFailed: 'Echec impression',
    conflict: 'Tableau mis a jour — reessayez',
    readyAfterMinutesLabel: 'Prepare → pret (attente)',
    readyAfterMinutesHint: 'Apres ce delai, les lignes affichent Pret pour tout le restaurant.',
    readyAfterMinutesUnit: 'min',
    readyAfterMinutesSave: 'Enregistrer',
    readyAfterMinutesSaved: 'Enregistre',
    readyAfterMinutesSaveFail: 'Echec enregistrement',
  },
  de: {
    screensTitle: 'Kuchenschirme',
    screensEmpty: 'Keine Schirme',
    screensEmptyHint: 'Bitten Sie den Inhaber, Schirme zu konfigurieren.',
    openScreen: 'Offnen',
    backToScreens: 'Zuruck',
    viewByTable: 'Nach Tisch',
    viewByDish: 'Nach Gericht',
    prep: 'Vorbereiten',
    prepBusy: 'Laeuft…',
    print: 'Drucken',
    printBusy: 'Druckt…',
    maximize: 'Maximieren',
    restore: 'Wiederherstellen',
    selectLines: 'Zeilen waehlen, dann vorbereiten',
    selectPrintLines: 'Zeilen waehlen, dann drucken',
    selectAll: 'Alles',
    deselectAll: 'Nichts',
    noLines: 'Keine offenen Gerichte',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.de.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.de.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.de.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.de.done,
    portionBadge: '{n} Stk',
    tablesCountBadge: '{n} Tische',
    tablesLabel: 'Tische: {tables}',
    waitMinutes: '{n} Min',
    expandGroup: 'Aufklappen',
    collapseGroup: 'Zuklappen',
    readyRailShow: 'Vorbereitet / fertig · {n}',
    readyRailHide: 'Ausblenden',
    readyRailEmpty: 'Keine vorbereiteten oder fertigen Gerichte',
    prepSuccess: 'Vorbereitet',
    prepFailed: 'Vorbereitung fehlgeschlagen',
    printSuccess: 'Gedruckt',
    printFailed: 'Druck fehlgeschlagen',
    conflict: 'Board aktualisiert — erneut versuchen',
    readyAfterMinutesLabel: 'Vorbereitet → fertig (Wartezeit)',
    readyAfterMinutesHint: 'Danach zeigen Zeilen Fertig im ganzen Restaurant.',
    readyAfterMinutesUnit: 'Min',
    readyAfterMinutesSave: 'Speichern',
    readyAfterMinutesSaved: 'Gespeichert',
    readyAfterMinutesSaveFail: 'Speichern fehlgeschlagen',
  },
};
