import type { UILanguage } from '@/lib/i18n';
import { KITCHEN_ITEM_STATUS_LABEL } from '@/lib/kitchen-progress-display';

/** Kitchen-screen UI copy (zh/en primary; others fall back to en). */
export const KITCHEN_SCREEN_TEXT: Record<
  UILanguage,
  {
    screensTitle: string;
    screensEmpty: string;
    screensEmptyHint: string;
    openScreen: string;
    backToScreens: string;
    viewByTable: string;
    viewByDish: string;
    prep: string;
    prepBusy: string;
    print: string;
    printBusy: string;
    maximize: string;
    restore: string;
    selectLines: string;
    selectPrintLines: string;
    selectAll: string;
    deselectAll: string;
    /** Sole table title on group headers, by-dish rows and the ready rail («90 桌»). */
    tableTitle: string;
    /** Group header summary part («N 道»; joined with « · » beside `portionBadge`). */
    dishCount: string;
    noLines: string;
    statusPending: string;
    statusCooking: string;
    statusReady: string;
    statusDone: string;
    /** By-dish row: workbench portion total for this dish (between n/m and name). */
    portionBadge: string;
    waitMinutes: string;
    expandGroup: string;
    collapseGroup: string;
    readyRailShow: string;
    readyRailHide: string;
    readyRailEmpty: string;
    /** Expanded bottom-rail zone title (duty label; not a second status vocabulary). */
    readyRailZoneTitle: string;
    prepSuccess: string;
    prepFailed: string;
    printSuccess: string;
    printFailed: string;
    conflict: string;
    /** Read-only dish detail modal confirm. */
    detailConfirm: string;
    detailDescriptionEmpty: string;
    detailAllergensTitle: string;
    detailAllergensUnmarked: string;
    detailVegetarianBadge: string;
    /** Aria for dish thumb that opens detail. */
    dishThumbOpenDetail: string;
    trayTitle: string;
    traySummary: string;
    trayEmpty: string;
    /** Shared by group headers and the prep tray: distinct tables / longest wait / «已选 n/m» tally. */
    tableCount: string;
    longestWait: string;
    selectedOf: string;
    trayClear: string;
    trayRemoveDish: string;
    trayClearAll: string;
    trayClearAllTitle: string;
    trayClearAllMessage: string;
    trayMoreTables: string;
    trayLessTables: string;
    trayCancel: string;
    /** Toast: tray rows that left「pending」(prepped / cancelled on another screen). */
    trayDroppedByOthers: string;
  }
> = {
  zh: {
    screensTitle: '后厨大屏',
    screensEmpty: '暂无大屏',
    screensEmptyHint: '请店主在设置中配置后厨大屏与档口。',
    openScreen: '打开',
    backToScreens: '返回大屏列表',
    viewByTable: '按桌',
    viewByDish: '按菜',
    prep: '备餐',
    prepBusy: '备餐中…',
    print: '打印',
    printBusy: '打印中…',
    maximize: '最大化',
    restore: '复原',
    selectLines: '勾选后点击备餐',
    selectPrintLines: '勾选后点击打印',
    selectAll: '全选',
    deselectAll: '取消全选',
    tableTitle: '{name} 桌',
    dishCount: '{n} 道',
    noLines: '暂无待备餐菜品',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.zh.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.zh.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.zh.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.zh.done,
    portionBadge: '共 {n} 份',
    waitMinutes: '等 {n} 分',
    expandGroup: '展开',
    collapseGroup: '收起',
    readyRailShow: '已备餐/已出餐 · {n}',
    readyRailHide: '收起',
    readyRailEmpty: '暂无已备餐或已出餐',
    readyRailZoneTitle: '补打区 · 已备餐 / 已出餐',
    prepSuccess: '已备餐',
    prepFailed: '备餐失败，请重试',
    printSuccess: '已打印',
    printFailed: '打印失败，请重试',
    conflict: '数据已更新，请重试',
    detailConfirm: '确认',
    detailDescriptionEmpty: '暂无菜品说明',
    detailAllergensTitle: '过敏原',
    detailAllergensUnmarked: '未标注',
    detailVegetarianBadge: '素食',
    dishThumbOpenDetail: '查看菜品详情',
    trayTitle: '备餐区',
    traySummary: '已选 {d} 道 · {p} 份 · {t} 桌',
    trayEmpty: '从左侧勾选要备的菜',
    tableCount: '{n} 桌',
    longestWait: '最久 {n} 分',
    selectedOf: '已选 {n}/{m}',
    trayClear: '清空',
    trayRemoveDish: '移出',
    trayClearAll: '清空全部',
    trayClearAllTitle: '清空备餐区',
    trayClearAllMessage: '所有勾选将取消，菜品仍留在列表中。',
    trayMoreTables: '+{n} 桌 展开',
    trayLessTables: '收起',
    trayCancel: '取消',
    trayDroppedByOthers: '{n} 行已被备餐或撤单，已从备餐区移除',
  },
  en: {
    screensTitle: 'Kitchen screens',
    screensEmpty: 'No screens configured',
    screensEmptyHint: 'Ask the owner to configure kitchen screens and stations in settings.',
    openScreen: 'Open',
    backToScreens: 'Back to screens',
    viewByTable: 'By table',
    viewByDish: 'By dish',
    prep: 'Prep',
    prepBusy: 'Prepping…',
    print: 'Print',
    printBusy: 'Printing…',
    maximize: 'Maximize',
    restore: 'Restore',
    selectLines: 'Select lines, then prep',
    selectPrintLines: 'Select lines, then print',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    tableTitle: 'Table {name}',
    dishCount: 'Dishes {n}',
    noLines: 'No dishes waiting',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.en.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.en.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.en.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.en.done,
    portionBadge: '{n} pcs',
    waitMinutes: '{n}m wait',
    expandGroup: 'Expand',
    collapseGroup: 'Collapse',
    readyRailShow: 'Prepped / ready · {n}',
    readyRailHide: 'Hide',
    readyRailEmpty: 'No prepped or ready dishes',
    readyRailZoneTitle: 'Reprint · Prepped / Ready',
    prepSuccess: 'Prepped',
    prepFailed: 'Prep failed — try again',
    printSuccess: 'Printed',
    printFailed: 'Print failed — try again',
    conflict: 'Board updated — please retry',
    detailConfirm: 'OK',
    detailDescriptionEmpty: 'No description',
    detailAllergensTitle: 'Allergens',
    detailAllergensUnmarked: 'Not marked',
    detailVegetarianBadge: 'Vegetarian',
    dishThumbOpenDetail: 'View dish details',
    trayTitle: 'Prep tray',
    traySummary: 'Dishes {d} · Pcs {p} · Tables {t}',
    trayEmpty: 'Select dishes on the left to prep',
    tableCount: 'Tables {n}',
    longestWait: 'Longest {n}m',
    selectedOf: '{n}/{m} selected',
    trayClear: 'Clear',
    trayRemoveDish: 'Remove',
    trayClearAll: 'Clear all',
    trayClearAllTitle: 'Clear prep tray?',
    trayClearAllMessage: 'All selections will be cleared; dishes stay in the list.',
    trayMoreTables: '+{n} tables',
    trayLessTables: 'Collapse',
    trayCancel: 'Cancel',
    trayDroppedByOthers: '{n} line(s) were prepped or cancelled elsewhere and left the tray',
  },
  pt: {
    screensTitle: 'Ecras de cozinha',
    screensEmpty: 'Sem ecras configurados',
    screensEmptyHint: 'Peca ao dono para configurar ecras e estacoes nas definicoes.',
    openScreen: 'Abrir',
    backToScreens: 'Voltar aos ecras',
    viewByTable: 'Por mesa',
    viewByDish: 'Por prato',
    prep: 'Preparar',
    prepBusy: 'A preparar…',
    print: 'Imprimir',
    printBusy: 'A imprimir…',
    maximize: 'Maximizar',
    restore: 'Restaurar',
    selectLines: 'Selecione e prepare',
    selectPrintLines: 'Selecione e imprima',
    selectAll: 'Selecionar tudo',
    deselectAll: 'Desmarcar',
    tableTitle: 'Mesa {name}',
    dishCount: 'Pratos {n}',
    noLines: 'Sem pratos a preparar',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.pt.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.pt.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.pt.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.pt.done,
    portionBadge: '{n} un.',
    waitMinutes: '{n} min',
    expandGroup: 'Expandir',
    collapseGroup: 'Recolher',
    readyRailShow: 'Preparado / pronto · {n}',
    readyRailHide: 'Ocultar',
    readyRailEmpty: 'Sem pratos preparados ou prontos',
    readyRailZoneTitle: 'Reimpressao · Preparado / Pronto',
    prepSuccess: 'Preparado',
    prepFailed: 'Falha ao preparar',
    printSuccess: 'Impresso',
    printFailed: 'Falha ao imprimir',
    conflict: 'Quadro atualizado — tente de novo',
    detailConfirm: 'Confirmar',
    detailDescriptionEmpty: 'Sem descricao',
    detailAllergensTitle: 'Alergenios',
    detailAllergensUnmarked: 'Nao marcado',
    detailVegetarianBadge: 'Vegetariano',
    dishThumbOpenDetail: 'Ver detalhes do prato',
    trayTitle: 'Área de preparo',
    traySummary: 'Pratos {d} · Un. {p} · Mesas {t}',
    trayEmpty: 'Selecione os pratos à esquerda',
    tableCount: 'Mesas {n}',
    longestWait: 'Máx. {n} min',
    selectedOf: '{n}/{m} selecionados',
    trayClear: 'Limpar',
    trayRemoveDish: 'Remover',
    trayClearAll: 'Limpar tudo',
    trayClearAllTitle: 'Limpar área de preparo?',
    trayClearAllMessage: 'Todas as seleções serão limpas; os pratos continuam na lista.',
    trayMoreTables: '+{n} mesas',
    trayLessTables: 'Recolher',
    trayCancel: 'Cancelar',
    trayDroppedByOthers: '{n} linha(s) preparada(s) ou cancelada(s) noutro local; saíram da área',
  },
  es: {
    screensTitle: 'Pantallas de cocina',
    screensEmpty: 'Sin pantallas',
    screensEmptyHint: 'Pida al dueno configurar pantallas y estaciones.',
    openScreen: 'Abrir',
    backToScreens: 'Volver',
    viewByTable: 'Por mesa',
    viewByDish: 'Por plato',
    prep: 'Preparar',
    prepBusy: 'Preparando…',
    print: 'Imprimir',
    printBusy: 'Imprimiendo…',
    maximize: 'Maximizar',
    restore: 'Restaurar',
    selectLines: 'Seleccione y prepare',
    selectPrintLines: 'Seleccione e imprima',
    selectAll: 'Seleccionar todo',
    deselectAll: 'Deseleccionar',
    tableTitle: 'Mesa {name}',
    dishCount: 'Platos {n}',
    noLines: 'Sin platos pendientes',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.es.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.es.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.es.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.es.done,
    portionBadge: '{n} uds',
    waitMinutes: '{n} min',
    expandGroup: 'Expandir',
    collapseGroup: 'Cerrar',
    readyRailShow: 'Preparado / listo · {n}',
    readyRailHide: 'Ocultar',
    readyRailEmpty: 'Sin platos preparados o listos',
    readyRailZoneTitle: 'Reimpresion · Preparado / Listo',
    prepSuccess: 'Preparado',
    prepFailed: 'Error al preparar',
    printSuccess: 'Impreso',
    printFailed: 'Error al imprimir',
    conflict: 'Tablero actualizado — reintente',
    detailConfirm: 'Confirmar',
    detailDescriptionEmpty: 'Sin descripcion',
    detailAllergensTitle: 'Alergenos',
    detailAllergensUnmarked: 'Sin marcar',
    detailVegetarianBadge: 'Vegetariano',
    dishThumbOpenDetail: 'Ver detalle del plato',
    trayTitle: 'Zona de preparación',
    traySummary: 'Platos {d} · Uds. {p} · Mesas {t}',
    trayEmpty: 'Seleccione platos a la izquierda',
    tableCount: 'Mesas {n}',
    longestWait: 'Máx. {n} min',
    selectedOf: '{n}/{m} seleccionados',
    trayClear: 'Limpiar',
    trayRemoveDish: 'Quitar',
    trayClearAll: 'Limpiar todo',
    trayClearAllTitle: '¿Limpiar zona de preparación?',
    trayClearAllMessage: 'Se quitarán todas las selecciones; los platos siguen en la lista.',
    trayMoreTables: '+{n} mesas',
    trayLessTables: 'Contraer',
    trayCancel: 'Cancelar',
    trayDroppedByOthers: '{n} línea(s) preparada(s) o cancelada(s) en otro lugar; salieron de la zona',
  },
  fr: {
    screensTitle: 'Ecrans cuisine',
    screensEmpty: 'Aucun ecran',
    screensEmptyHint: 'Demandez au gerant de configurer les ecrans.',
    openScreen: 'Ouvrir',
    backToScreens: 'Retour',
    viewByTable: 'Par table',
    viewByDish: 'Par plat',
    prep: 'Preparer',
    prepBusy: 'Preparation…',
    print: 'Imprimer',
    printBusy: 'Impression…',
    maximize: 'Agrandir',
    restore: 'Restaurer',
    selectLines: 'Selectionnez puis preparez',
    selectPrintLines: 'Selectionnez puis imprimez',
    selectAll: 'Tout select.',
    deselectAll: 'Tout deselect.',
    tableTitle: 'Table {name}',
    dishCount: 'Plats {n}',
    noLines: 'Aucun plat en attente',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.fr.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.fr.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.fr.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.fr.done,
    portionBadge: '{n} pcs',
    waitMinutes: '{n} min',
    expandGroup: 'Ouvrir',
    collapseGroup: 'Fermer',
    readyRailShow: 'Prepare / pret · {n}',
    readyRailHide: 'Masquer',
    readyRailEmpty: 'Aucun plat prepare ou pret',
    readyRailZoneTitle: 'Reimpression · Prepare / Pret',
    prepSuccess: 'Prepare',
    prepFailed: 'Echec preparation',
    printSuccess: 'Imprime',
    printFailed: 'Echec impression',
    conflict: 'Tableau mis a jour — reessayez',
    detailConfirm: 'Confirmer',
    detailDescriptionEmpty: 'Pas de description',
    detailAllergensTitle: 'Allergenes',
    detailAllergensUnmarked: 'Non indique',
    detailVegetarianBadge: 'Vegetarien',
    dishThumbOpenDetail: 'Voir le detail du plat',
    trayTitle: 'Zone de préparation',
    traySummary: 'Plats {d} · Pcs {p} · Tables {t}',
    trayEmpty: 'Sélectionnez les plats à gauche',
    tableCount: 'Tables {n}',
    longestWait: 'Max {n} min',
    selectedOf: '{n}/{m} sélectionnés',
    trayClear: 'Vider',
    trayRemoveDish: 'Retirer',
    trayClearAll: 'Tout vider',
    trayClearAllTitle: 'Vider la zone de préparation ?',
    trayClearAllMessage: 'Toutes les sélections seront effacées ; les plats restent dans la liste.',
    trayMoreTables: '+{n} tables',
    trayLessTables: 'Réduire',
    trayCancel: 'Annuler',
    trayDroppedByOthers: '{n} ligne(s) préparée(s) ou annulée(s) ailleurs, retirée(s) de la zone',
  },
  de: {
    screensTitle: 'Kuchenschirme',
    screensEmpty: 'Keine Schirme',
    screensEmptyHint: 'Bitten Sie den Inhaber, Schirme zu konfigurieren.',
    openScreen: 'Offnen',
    backToScreens: 'Zuruck',
    viewByTable: 'Nach Tisch',
    viewByDish: 'Nach Gericht',
    prep: 'Vorbereiten',
    prepBusy: 'Laeuft…',
    print: 'Drucken',
    printBusy: 'Druckt…',
    maximize: 'Maximieren',
    restore: 'Wiederherstellen',
    selectLines: 'Zeilen waehlen, dann vorbereiten',
    selectPrintLines: 'Zeilen waehlen, dann drucken',
    selectAll: 'Alles',
    deselectAll: 'Nichts',
    tableTitle: 'Tisch {name}',
    dishCount: 'Gerichte {n}',
    noLines: 'Keine offenen Gerichte',
    statusPending: KITCHEN_ITEM_STATUS_LABEL.de.pending,
    statusCooking: KITCHEN_ITEM_STATUS_LABEL.de.cooking,
    statusReady: KITCHEN_ITEM_STATUS_LABEL.de.ready,
    statusDone: KITCHEN_ITEM_STATUS_LABEL.de.done,
    portionBadge: '{n} Stk',
    waitMinutes: '{n} Min',
    expandGroup: 'Aufklappen',
    collapseGroup: 'Zuklappen',
    readyRailShow: 'Vorbereitet / fertig · {n}',
    readyRailHide: 'Ausblenden',
    readyRailEmpty: 'Keine vorbereiteten oder fertigen Gerichte',
    readyRailZoneTitle: 'Nachdruck · Vorbereitet / Fertig',
    prepSuccess: 'Vorbereitet',
    prepFailed: 'Vorbereitung fehlgeschlagen',
    printSuccess: 'Gedruckt',
    printFailed: 'Druck fehlgeschlagen',
    conflict: 'Board aktualisiert — erneut versuchen',
    detailConfirm: 'OK',
    detailDescriptionEmpty: 'Keine Beschreibung',
    detailAllergensTitle: 'Allergene',
    detailAllergensUnmarked: 'Nicht markiert',
    detailVegetarianBadge: 'Vegetarisch',
    dishThumbOpenDetail: 'Gerichtdetails anzeigen',
    trayTitle: 'Zubereitung',
    traySummary: 'Gerichte {d} · Stk. {p} · Tische {t}',
    trayEmpty: 'Gerichte links auswählen',
    tableCount: 'Tische {n}',
    longestWait: 'Max. {n} Min.',
    selectedOf: '{n}/{m} gewählt',
    trayClear: 'Leeren',
    trayRemoveDish: 'Entfernen',
    trayClearAll: 'Alle leeren',
    trayClearAllTitle: 'Zubereitung leeren?',
    trayClearAllMessage: 'Alle Auswahlen werden gelöscht; die Gerichte bleiben in der Liste.',
    trayMoreTables: '+{n} Tische',
    trayLessTables: 'Einklappen',
    trayCancel: 'Abbrechen',
    trayDroppedByOthers: '{n} Zeile(n) anderswo zubereitet oder storniert und entfernt',
  },
};
