#!/usr/bin/env bash
# Create/update .env.local.dev from `supabase status` (gitignored).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.env.local.dev"
cd "$ROOT"

if ! supabase status >/dev/null 2>&1; then
  echo "Run supabase start first." >&2
  exit 1
fi

eval "$(supabase status -o env 2>/dev/null | grep -E '^(API_URL|ANON_KEY|SERVICE_ROLE_KEY)=')"

if [[ -z "${API_URL:-}" || -z "${ANON_KEY:-}" || -z "${SERVICE_ROLE_KEY:-}" ]]; then
  echo "Could not read keys from supabase status -o env" >&2
  exit 1
fi

if [[ ! -f "$OUT" ]]; then
  cat >"$OUT" <<'EOF'
# Local Docker Supabase — generated by scripts/sync-local-supabase-env.sh
# Login (seed): dev-owner@local.test / localdev123 — slug: restaurant-mo9y14xc
# Usage: npm run dev  (or pnpm run dev)

NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
NEXT_PUBLIC_BASE_URL=http://localhost:3000
ADMIN_BOOTSTRAP_SECRET=change-me-local-admin-secret
PRINT_AGENT_JWT_SECRET=change-me-local-print-agent-jwt-32c
STAFF_SESSION_SECRET=change-me-local-staff-session-32c
ORDER_ENQUEUE_SECRET=change-me-local-order-enqueue-32c
NEXT_PUBLIC_PRINT_AGENT_GITHUB_REPO=jianping2024/restaurant-ordering
EOF
fi

update_var() {
  local key="$1" val="$2" file="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i.bak "s|^${key}=.*|${key}=${val}|" "$file" && rm -f "${file}.bak"
  else
    echo "${key}=${val}" >>"$file"
  fi
}

update_var NEXT_PUBLIC_SUPABASE_URL "$API_URL" "$OUT"
update_var NEXT_PUBLIC_SUPABASE_ANON_KEY "$ANON_KEY" "$OUT"
update_var SUPABASE_SERVICE_ROLE_KEY "$SERVICE_ROLE_KEY" "$OUT"

echo "Updated Supabase URL/keys in .env.local.dev"
echo "Run: npm run dev"
