#!/usr/bin/env bash
# Generate deploy/on-prem/.env from local `supabase status` (POC Mode A).
# Does not print secrets. Overwrites .env in this directory.
set -euo pipefail

ONPREM_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT="${ONPREM_DIR}/.env"

if ! command -v supabase >/dev/null 2>&1; then
  echo "supabase CLI not found" >&2
  exit 1
fi

cd "$ROOT"
if ! supabase status >/dev/null 2>&1; then
  echo "Could not read supabase status. Run: supabase start" >&2
  exit 1
fi

# shellcheck disable=SC1090
eval "$(supabase status -o env 2>/dev/null | grep -E '^(API_URL|ANON_KEY|SERVICE_ROLE_KEY)=')"

if [[ -z "${API_URL:-}" || -z "${ANON_KEY:-}" || -z "${SERVICE_ROLE_KEY:-}" ]]; then
  echo "Could not parse API_URL/ANON_KEY/SERVICE_ROLE_KEY from supabase status -o env" >&2
  exit 1
fi

# Inside the web container, reach host Supabase API (not inlined at build).
SERVER_URL="${MESA_SERVER_SUPABASE_URL:-http://host.docker.internal:54321}"
# Browser on the host machine talks to supabase start on loopback.
PUBLIC_URL="${MESA_PUBLIC_SUPABASE_URL:-${API_URL}}"

JWT_SECRET="$(openssl rand -hex 32)"
CRON_SECRET="$(openssl rand -hex 24)"

umask 077
cat >"$OUT" <<EOF
# Generated by scripts/generate-env.sh — do not commit
MESA_ON_PREM=1
MESA_WEB_PORT=3000
NEXT_PUBLIC_BASE_URL=http://127.0.0.1:3000
NEXT_PUBLIC_SUPABASE_URL=${PUBLIC_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_URL=${SERVER_URL}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
PRINT_AGENT_JWT_SECRET=${JWT_SECRET}
STAFF_SESSION_SECRET=${JWT_SECRET}
ORDER_ENQUEUE_SECRET=${JWT_SECRET}
CRON_SECRET=${CRON_SECRET}
EOF

echo "Wrote ${OUT} (secrets not echoed)."
echo "Compose: SUPABASE_URL=${SERVER_URL} (server); NEXT_PUBLIC_SUPABASE_URL=${PUBLIC_URL} (browser)."
echo "Host-side next start: leave SUPABASE_URL unset or equal to ${API_URL}."
